# Generated by Django 3.0.5 on 2020-04-11 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.IntegerField()),
                ('rows', models.IntegerField()),
                ('mines', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('I', 'Initial'), ('S', 'Started'), ('W', 'Won'), ('L', 'Lost')], default='I', max_length=1)),
                ('started_time', models.DateTimeField(blank=True, null=True)),
                ('ended_time', models.DateTimeField(blank=True, null=True)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Matrix')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=True)),
                ('has_flag', models.BooleanField(default=False)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Matrix')),
            ],
        ),
    ]
